# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-06 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_number', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_namу', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark1', models.CharField(choices=[('1', 'Полностью не согласен'), ('2', 'Скорее не согласен'), ('3', 'Отчасти согласен'), ('4', 'Скорее согласен'), ('5', 'Полностью согласен')], max_length=1)),
                ('mark2', models.CharField(choices=[('1', 'Полностью не согласен'), ('2', 'Скорее не согласен'), ('3', 'Отчасти согласен'), ('4', 'Скорее согласен'), ('5', 'Полностью согласен')], max_length=1)),
                ('mark3', models.CharField(choices=[('1', 'Полностью не согласен'), ('2', 'Скорее не согласен'), ('3', 'Отчасти согласен'), ('4', 'Скорее согласен'), ('5', 'Полностью согласен')], max_length=1)),
                ('mark4', models.CharField(choices=[('1', 'Полностью не согласен'), ('2', 'Скорее не согласен'), ('3', 'Отчасти согласен'), ('4', 'Скорее согласен'), ('5', 'Полностью согласен')], max_length=1)),
                ('mark5', models.CharField(choices=[('1', 'Полностью не согласен'), ('2', 'Скорее не согласен'), ('3', 'Отчасти согласен'), ('4', 'Скорее согласен'), ('5', 'Полностью согласен')], max_length=1)),
                ('mark6', models.CharField(choices=[('1', 'Полностью не согласен'), ('2', 'Скорее не согласен'), ('3', 'Отчасти согласен'), ('4', 'Скорее согласен'), ('5', 'Полностью согласен')], max_length=1)),
                ('mark7', models.CharField(choices=[('1', 'Полностью не согласен'), ('2', 'Скорее не согласен'), ('3', 'Отчасти согласен'), ('4', 'Скорее согласен'), ('5', 'Полностью согласен')], max_length=1)),
                ('mark8', models.CharField(choices=[('1', 'Полностью не согласен'), ('2', 'Скорее не согласен'), ('3', 'Отчасти согласен'), ('4', 'Скорее согласен'), ('5', 'Полностью согласен')], max_length=1)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='response',
            name='votes',
            field=models.ManyToManyField(to='app.Vote'),
        ),
        migrations.AddField(
            model_name='group',
            name='teachers',
            field=models.ManyToManyField(to='app.Teacher'),
        ),
        migrations.AddField(
            model_name='department',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Institute'),
        ),
    ]
