# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-08 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='middle_namу',
            new_name='middle_name',
        ),
        migrations.AlterField(
            model_name='group',
            name='teachers',
            field=models.ManyToManyField(null=True, to='app.Teacher'),
        ),
        migrations.AlterField(
            model_name='response',
            name='votes',
            field=models.ManyToManyField(null=True, to='app.Vote'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Department'),
        ),
    ]
