# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-08 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171208_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='votes',
        ),
        migrations.AddField(
            model_name='vote',
            name='response',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='app.Response'),
            preserve_default=False,
        ),
    ]
