# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20171208_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='student_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='vote',
            name='mark1',
            field=models.CharField(choices=[('0', 'Выберите'), ('1', '1 балл'), ('2', '2 балла'), ('3', '3 балла'), ('4', '4 балла'), ('5', '5 баллов')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='vote',
            name='mark2',
            field=models.CharField(choices=[('0', 'Выберите'), ('1', '1 балл'), ('2', '2 балла'), ('3', '3 балла'), ('4', '4 балла'), ('5', '5 баллов')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='vote',
            name='mark3',
            field=models.CharField(choices=[('0', 'Выберите'), ('1', '1 балл'), ('2', '2 балла'), ('3', '3 балла'), ('4', '4 балла'), ('5', '5 баллов')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='vote',
            name='mark4',
            field=models.CharField(choices=[('0', 'Выберите'), ('1', '1 балл'), ('2', '2 балла'), ('3', '3 балла'), ('4', '4 балла'), ('5', '5 баллов')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='vote',
            name='mark5',
            field=models.CharField(choices=[('0', 'Выберите'), ('1', '1 балл'), ('2', '2 балла'), ('3', '3 балла'), ('4', '4 балла'), ('5', '5 баллов')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='vote',
            name='mark6',
            field=models.CharField(choices=[('0', 'Выберите'), ('1', '1 балл'), ('2', '2 балла'), ('3', '3 балла'), ('4', '4 балла'), ('5', '5 баллов')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='vote',
            name='mark7',
            field=models.CharField(choices=[('0', 'Выберите'), ('1', '1 балл'), ('2', '2 балла'), ('3', '3 балла'), ('4', '4 балла'), ('5', '5 баллов')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='vote',
            name='mark8',
            field=models.CharField(choices=[('0', 'Выберите'), ('1', '1 балл'), ('2', '2 балла'), ('3', '3 балла'), ('4', '4 балла'), ('5', '5 баллов')], default='0', max_length=1),
        ),
    ]
