# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171217_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='student_name',
        ),
        migrations.AddField(
            model_name='response',
            name='student_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
