# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20171217_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='badge_number',
            field=models.CharField(max_length=100),
        ),
    ]
