# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20171217_2005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='ResponseStudent',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='response',
            new_name='response_student',
        ),
    ]
