# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-26 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20171217_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='app.Teacher'),
        ),
    ]
